### ISSUE TITLE
Have you considered RUST?

### ISSUE THREAD

**Issue by OhBonsai** [Wonder-Technology/Meta3D#2]
Hi yyc:
  Old fans from wonder 2017....  Have you considered RUST?
  
  The most interesting thing I've read recently is that there is a WebGPU Rust project where you can use that API for desktop development, not tied to a browser.

**Comment by yyc-git** [comment]
Hello~
There is a [WebGPU Node](https://github.com/maierfelix/webgpu) project which provide WebGPU api with javascript. It run in node.js, so can be used for desktop development.
More can see [WebGPU+光线追踪Ray Tracing 开发三个月总结](https://www.cnblogs.com/chaogex/p/13199224.html)

So Meta3D use typescript and rescript, not consider RUST now. Thanks for your suggestion~
